### ISSUE TITLE
Add shipping/dimensions feature

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-snipcart#1]
Snipcart will need dimensions if a shipping provider is added. (see https://docs.snipcart.com/v3/setup/products#advanced-product-attributes)

We should use a dimension map listing potential info:

```
product:
    dimensions:
      weight: 195
      width: 34
      length: 100
      height: 22
```

Note that `weight` is an integer in grams while the rest are integers in cm

Potentially linked to https://github.com/theNewDynamic/oregonsadventurecoast.com/issues/143
